//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('woody_js/dist/thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var base_ttypes = require('./base_types');
var domain_ttypes = require('./domain_types');
var user_interaction_ttypes = require('./user_interaction_types');


var ttypes = require('./payment_processing_types');
//HELPER FUNCTIONS AND STRUCTURES

var RecurrentPaymentTools_Create_args = function(args) {
  this.params = null;
  if (args) {
    if (args.params !== undefined && args.params !== null) {
      this.params = new ttypes.RecurrentPaymentToolParams(args.params);
    }
  }
};
RecurrentPaymentTools_Create_args.prototype = {};
RecurrentPaymentTools_Create_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.params = new ttypes.RecurrentPaymentToolParams();
        this.params.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecurrentPaymentTools_Create_args.prototype.write = function(output) {
  output.writeStructBegin('RecurrentPaymentTools_Create_args');
  if (this.params !== null && this.params !== undefined) {
    output.writeFieldBegin('params', Thrift.Type.STRUCT, 1);
    this.params.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RecurrentPaymentTools_Create_result = function(args) {
  this.success = null;
  this.invalid_user = null;
  this.invalid_party_status = null;
  this.invalid_shop_status = null;
  this.shop_not_found = null;
  this.party_not_found = null;
  this.invalid_contract_status = null;
  this.operation_not_permitted = null;
  this.invalid_payment_method = null;
  if (args instanceof ttypes.InvalidUser) {
    this.invalid_user = args;
    return;
  }
  if (args instanceof ttypes.InvalidPartyStatus) {
    this.invalid_party_status = args;
    return;
  }
  if (args instanceof ttypes.InvalidShopStatus) {
    this.invalid_shop_status = args;
    return;
  }
  if (args instanceof ttypes.ShopNotFound) {
    this.shop_not_found = args;
    return;
  }
  if (args instanceof ttypes.PartyNotFound) {
    this.party_not_found = args;
    return;
  }
  if (args instanceof ttypes.InvalidContractStatus) {
    this.invalid_contract_status = args;
    return;
  }
  if (args instanceof ttypes.OperationNotPermitted) {
    this.operation_not_permitted = args;
    return;
  }
  if (args instanceof ttypes.InvalidPaymentMethod) {
    this.invalid_payment_method = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.RecurrentPaymentTool(args.success);
    }
    if (args.invalid_user !== undefined && args.invalid_user !== null) {
      this.invalid_user = args.invalid_user;
    }
    if (args.invalid_party_status !== undefined && args.invalid_party_status !== null) {
      this.invalid_party_status = args.invalid_party_status;
    }
    if (args.invalid_shop_status !== undefined && args.invalid_shop_status !== null) {
      this.invalid_shop_status = args.invalid_shop_status;
    }
    if (args.shop_not_found !== undefined && args.shop_not_found !== null) {
      this.shop_not_found = args.shop_not_found;
    }
    if (args.party_not_found !== undefined && args.party_not_found !== null) {
      this.party_not_found = args.party_not_found;
    }
    if (args.invalid_contract_status !== undefined && args.invalid_contract_status !== null) {
      this.invalid_contract_status = args.invalid_contract_status;
    }
    if (args.operation_not_permitted !== undefined && args.operation_not_permitted !== null) {
      this.operation_not_permitted = args.operation_not_permitted;
    }
    if (args.invalid_payment_method !== undefined && args.invalid_payment_method !== null) {
      this.invalid_payment_method = args.invalid_payment_method;
    }
  }
};
RecurrentPaymentTools_Create_result.prototype = {};
RecurrentPaymentTools_Create_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.RecurrentPaymentTool();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.invalid_user = new ttypes.InvalidUser();
        this.invalid_user.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.invalid_party_status = new ttypes.InvalidPartyStatus();
        this.invalid_party_status.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.invalid_shop_status = new ttypes.InvalidShopStatus();
        this.invalid_shop_status.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRUCT) {
        this.shop_not_found = new ttypes.ShopNotFound();
        this.shop_not_found.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.STRUCT) {
        this.party_not_found = new ttypes.PartyNotFound();
        this.party_not_found.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.STRUCT) {
        this.invalid_contract_status = new ttypes.InvalidContractStatus();
        this.invalid_contract_status.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRUCT) {
        this.operation_not_permitted = new ttypes.OperationNotPermitted();
        this.operation_not_permitted.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 8:
      if (ftype == Thrift.Type.STRUCT) {
        this.invalid_payment_method = new ttypes.InvalidPaymentMethod();
        this.invalid_payment_method.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecurrentPaymentTools_Create_result.prototype.write = function(output) {
  output.writeStructBegin('RecurrentPaymentTools_Create_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.invalid_user !== null && this.invalid_user !== undefined) {
    output.writeFieldBegin('invalid_user', Thrift.Type.STRUCT, 1);
    this.invalid_user.write(output);
    output.writeFieldEnd();
  }
  if (this.invalid_party_status !== null && this.invalid_party_status !== undefined) {
    output.writeFieldBegin('invalid_party_status', Thrift.Type.STRUCT, 2);
    this.invalid_party_status.write(output);
    output.writeFieldEnd();
  }
  if (this.invalid_shop_status !== null && this.invalid_shop_status !== undefined) {
    output.writeFieldBegin('invalid_shop_status', Thrift.Type.STRUCT, 3);
    this.invalid_shop_status.write(output);
    output.writeFieldEnd();
  }
  if (this.shop_not_found !== null && this.shop_not_found !== undefined) {
    output.writeFieldBegin('shop_not_found', Thrift.Type.STRUCT, 4);
    this.shop_not_found.write(output);
    output.writeFieldEnd();
  }
  if (this.party_not_found !== null && this.party_not_found !== undefined) {
    output.writeFieldBegin('party_not_found', Thrift.Type.STRUCT, 5);
    this.party_not_found.write(output);
    output.writeFieldEnd();
  }
  if (this.invalid_contract_status !== null && this.invalid_contract_status !== undefined) {
    output.writeFieldBegin('invalid_contract_status', Thrift.Type.STRUCT, 6);
    this.invalid_contract_status.write(output);
    output.writeFieldEnd();
  }
  if (this.operation_not_permitted !== null && this.operation_not_permitted !== undefined) {
    output.writeFieldBegin('operation_not_permitted', Thrift.Type.STRUCT, 7);
    this.operation_not_permitted.write(output);
    output.writeFieldEnd();
  }
  if (this.invalid_payment_method !== null && this.invalid_payment_method !== undefined) {
    output.writeFieldBegin('invalid_payment_method', Thrift.Type.STRUCT, 8);
    this.invalid_payment_method.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RecurrentPaymentTools_Abandon_args = function(args) {
  this.id = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
  }
};
RecurrentPaymentTools_Abandon_args.prototype = {};
RecurrentPaymentTools_Abandon_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecurrentPaymentTools_Abandon_args.prototype.write = function(output) {
  output.writeStructBegin('RecurrentPaymentTools_Abandon_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RecurrentPaymentTools_Abandon_result = function(args) {
  this.success = null;
  this.invalid_user = null;
  this.rec_payment_tool_not_found = null;
  this.invalid_rec_payment_tool_status = null;
  if (args instanceof ttypes.InvalidUser) {
    this.invalid_user = args;
    return;
  }
  if (args instanceof ttypes.RecurrentPaymentToolNotFound) {
    this.rec_payment_tool_not_found = args;
    return;
  }
  if (args instanceof ttypes.InvalidRecurrentPaymentToolStatus) {
    this.invalid_rec_payment_tool_status = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.RecurrentPaymentTool(args.success);
    }
    if (args.invalid_user !== undefined && args.invalid_user !== null) {
      this.invalid_user = args.invalid_user;
    }
    if (args.rec_payment_tool_not_found !== undefined && args.rec_payment_tool_not_found !== null) {
      this.rec_payment_tool_not_found = args.rec_payment_tool_not_found;
    }
    if (args.invalid_rec_payment_tool_status !== undefined && args.invalid_rec_payment_tool_status !== null) {
      this.invalid_rec_payment_tool_status = args.invalid_rec_payment_tool_status;
    }
  }
};
RecurrentPaymentTools_Abandon_result.prototype = {};
RecurrentPaymentTools_Abandon_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.RecurrentPaymentTool();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.invalid_user = new ttypes.InvalidUser();
        this.invalid_user.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.rec_payment_tool_not_found = new ttypes.RecurrentPaymentToolNotFound();
        this.rec_payment_tool_not_found.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.invalid_rec_payment_tool_status = new ttypes.InvalidRecurrentPaymentToolStatus();
        this.invalid_rec_payment_tool_status.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecurrentPaymentTools_Abandon_result.prototype.write = function(output) {
  output.writeStructBegin('RecurrentPaymentTools_Abandon_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.invalid_user !== null && this.invalid_user !== undefined) {
    output.writeFieldBegin('invalid_user', Thrift.Type.STRUCT, 1);
    this.invalid_user.write(output);
    output.writeFieldEnd();
  }
  if (this.rec_payment_tool_not_found !== null && this.rec_payment_tool_not_found !== undefined) {
    output.writeFieldBegin('rec_payment_tool_not_found', Thrift.Type.STRUCT, 2);
    this.rec_payment_tool_not_found.write(output);
    output.writeFieldEnd();
  }
  if (this.invalid_rec_payment_tool_status !== null && this.invalid_rec_payment_tool_status !== undefined) {
    output.writeFieldBegin('invalid_rec_payment_tool_status', Thrift.Type.STRUCT, 3);
    this.invalid_rec_payment_tool_status.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RecurrentPaymentTools_Get_args = function(args) {
  this.id = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
  }
};
RecurrentPaymentTools_Get_args.prototype = {};
RecurrentPaymentTools_Get_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecurrentPaymentTools_Get_args.prototype.write = function(output) {
  output.writeStructBegin('RecurrentPaymentTools_Get_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RecurrentPaymentTools_Get_result = function(args) {
  this.success = null;
  this.invalid_user = null;
  this.rec_payment_tool_not_found = null;
  if (args instanceof ttypes.InvalidUser) {
    this.invalid_user = args;
    return;
  }
  if (args instanceof ttypes.RecurrentPaymentToolNotFound) {
    this.rec_payment_tool_not_found = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.RecurrentPaymentTool(args.success);
    }
    if (args.invalid_user !== undefined && args.invalid_user !== null) {
      this.invalid_user = args.invalid_user;
    }
    if (args.rec_payment_tool_not_found !== undefined && args.rec_payment_tool_not_found !== null) {
      this.rec_payment_tool_not_found = args.rec_payment_tool_not_found;
    }
  }
};
RecurrentPaymentTools_Get_result.prototype = {};
RecurrentPaymentTools_Get_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.RecurrentPaymentTool();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.invalid_user = new ttypes.InvalidUser();
        this.invalid_user.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.rec_payment_tool_not_found = new ttypes.RecurrentPaymentToolNotFound();
        this.rec_payment_tool_not_found.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecurrentPaymentTools_Get_result.prototype.write = function(output) {
  output.writeStructBegin('RecurrentPaymentTools_Get_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.invalid_user !== null && this.invalid_user !== undefined) {
    output.writeFieldBegin('invalid_user', Thrift.Type.STRUCT, 1);
    this.invalid_user.write(output);
    output.writeFieldEnd();
  }
  if (this.rec_payment_tool_not_found !== null && this.rec_payment_tool_not_found !== undefined) {
    output.writeFieldBegin('rec_payment_tool_not_found', Thrift.Type.STRUCT, 2);
    this.rec_payment_tool_not_found.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RecurrentPaymentTools_GetEvents_args = function(args) {
  this.id = null;
  this.range = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
    if (args.range !== undefined && args.range !== null) {
      this.range = new ttypes.EventRange(args.range);
    }
  }
};
RecurrentPaymentTools_GetEvents_args.prototype = {};
RecurrentPaymentTools_GetEvents_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.id = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.range = new ttypes.EventRange();
        this.range.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecurrentPaymentTools_GetEvents_args.prototype.write = function(output) {
  output.writeStructBegin('RecurrentPaymentTools_GetEvents_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.STRING, 1);
    output.writeString(this.id);
    output.writeFieldEnd();
  }
  if (this.range !== null && this.range !== undefined) {
    output.writeFieldBegin('range', Thrift.Type.STRUCT, 2);
    this.range.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RecurrentPaymentTools_GetEvents_result = function(args) {
  this.success = null;
  this.invalid_user = null;
  this.rec_payment_tool_not_found = null;
  this.event_not_found = null;
  if (args instanceof ttypes.InvalidUser) {
    this.invalid_user = args;
    return;
  }
  if (args instanceof ttypes.RecurrentPaymentToolNotFound) {
    this.rec_payment_tool_not_found = args;
    return;
  }
  if (args instanceof ttypes.EventNotFound) {
    this.event_not_found = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [null]);
    }
    if (args.invalid_user !== undefined && args.invalid_user !== null) {
      this.invalid_user = args.invalid_user;
    }
    if (args.rec_payment_tool_not_found !== undefined && args.rec_payment_tool_not_found !== null) {
      this.rec_payment_tool_not_found = args.rec_payment_tool_not_found;
    }
    if (args.event_not_found !== undefined && args.event_not_found !== null) {
      this.event_not_found = args.event_not_found;
    }
  }
};
RecurrentPaymentTools_GetEvents_result.prototype = {};
RecurrentPaymentTools_GetEvents_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        var _size136 = 0;
        var _rtmp3140;
        this.success = [];
        var _etype139 = 0;
        _rtmp3140 = input.readListBegin();
        _etype139 = _rtmp3140.etype;
        _size136 = _rtmp3140.size;
        for (var _i141 = 0; _i141 < _size136; ++_i141)
        {
          var elem142 = null;
          elem142 = new ttypes.RecurrentPaymentToolEvent();
          elem142.read(input);
          this.success.push(elem142);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.invalid_user = new ttypes.InvalidUser();
        this.invalid_user.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.rec_payment_tool_not_found = new ttypes.RecurrentPaymentToolNotFound();
        this.rec_payment_tool_not_found.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRUCT) {
        this.event_not_found = new ttypes.EventNotFound();
        this.event_not_found.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

RecurrentPaymentTools_GetEvents_result.prototype.write = function(output) {
  output.writeStructBegin('RecurrentPaymentTools_GetEvents_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter143 in this.success)
    {
      if (this.success.hasOwnProperty(iter143))
      {
        iter143 = this.success[iter143];
        iter143.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  if (this.invalid_user !== null && this.invalid_user !== undefined) {
    output.writeFieldBegin('invalid_user', Thrift.Type.STRUCT, 1);
    this.invalid_user.write(output);
    output.writeFieldEnd();
  }
  if (this.rec_payment_tool_not_found !== null && this.rec_payment_tool_not_found !== undefined) {
    output.writeFieldBegin('rec_payment_tool_not_found', Thrift.Type.STRUCT, 2);
    this.rec_payment_tool_not_found.write(output);
    output.writeFieldEnd();
  }
  if (this.event_not_found !== null && this.event_not_found !== undefined) {
    output.writeFieldBegin('event_not_found', Thrift.Type.STRUCT, 3);
    this.event_not_found.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var RecurrentPaymentToolsClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
RecurrentPaymentToolsClient.prototype = {};
RecurrentPaymentToolsClient.prototype.seqid = function() { return this._seqid; }
RecurrentPaymentToolsClient.prototype.new_seqid = function() { return this._seqid += 1; }
RecurrentPaymentToolsClient.prototype.Create = function(params, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_Create(params);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_Create(params);
  }
};

RecurrentPaymentToolsClient.prototype.send_Create = function(params) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('Create', Thrift.MessageType.CALL, this.seqid());
  var args = new RecurrentPaymentTools_Create_args();
  args.params = params;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

RecurrentPaymentToolsClient.prototype.recv_Create = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new RecurrentPaymentTools_Create_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.invalid_user) {
    return callback(result.invalid_user);
  }
  if (null !== result.invalid_party_status) {
    return callback(result.invalid_party_status);
  }
  if (null !== result.invalid_shop_status) {
    return callback(result.invalid_shop_status);
  }
  if (null !== result.shop_not_found) {
    return callback(result.shop_not_found);
  }
  if (null !== result.party_not_found) {
    return callback(result.party_not_found);
  }
  if (null !== result.invalid_contract_status) {
    return callback(result.invalid_contract_status);
  }
  if (null !== result.operation_not_permitted) {
    return callback(result.operation_not_permitted);
  }
  if (null !== result.invalid_payment_method) {
    return callback(result.invalid_payment_method);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('Create failed: unknown result');
};
RecurrentPaymentToolsClient.prototype.Abandon = function(id, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_Abandon(id);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_Abandon(id);
  }
};

RecurrentPaymentToolsClient.prototype.send_Abandon = function(id) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('Abandon', Thrift.MessageType.CALL, this.seqid());
  var args = new RecurrentPaymentTools_Abandon_args();
  args.id = id;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

RecurrentPaymentToolsClient.prototype.recv_Abandon = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new RecurrentPaymentTools_Abandon_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.invalid_user) {
    return callback(result.invalid_user);
  }
  if (null !== result.rec_payment_tool_not_found) {
    return callback(result.rec_payment_tool_not_found);
  }
  if (null !== result.invalid_rec_payment_tool_status) {
    return callback(result.invalid_rec_payment_tool_status);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('Abandon failed: unknown result');
};
RecurrentPaymentToolsClient.prototype.Get = function(id, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_Get(id);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_Get(id);
  }
};

RecurrentPaymentToolsClient.prototype.send_Get = function(id) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('Get', Thrift.MessageType.CALL, this.seqid());
  var args = new RecurrentPaymentTools_Get_args();
  args.id = id;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

RecurrentPaymentToolsClient.prototype.recv_Get = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new RecurrentPaymentTools_Get_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.invalid_user) {
    return callback(result.invalid_user);
  }
  if (null !== result.rec_payment_tool_not_found) {
    return callback(result.rec_payment_tool_not_found);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('Get failed: unknown result');
};
RecurrentPaymentToolsClient.prototype.GetEvents = function(id, range, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_GetEvents(id, range);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_GetEvents(id, range);
  }
};

RecurrentPaymentToolsClient.prototype.send_GetEvents = function(id, range) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('GetEvents', Thrift.MessageType.CALL, this.seqid());
  var args = new RecurrentPaymentTools_GetEvents_args();
  args.id = id;
  args.range = range;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

RecurrentPaymentToolsClient.prototype.recv_GetEvents = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new RecurrentPaymentTools_GetEvents_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.invalid_user) {
    return callback(result.invalid_user);
  }
  if (null !== result.rec_payment_tool_not_found) {
    return callback(result.rec_payment_tool_not_found);
  }
  if (null !== result.event_not_found) {
    return callback(result.event_not_found);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('GetEvents failed: unknown result');
};
var RecurrentPaymentToolsProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
RecurrentPaymentToolsProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

RecurrentPaymentToolsProcessor.prototype.process_Create = function(seqid, input, output) {
  var args = new RecurrentPaymentTools_Create_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.Create.length === 1) {
    Q.fcall(this._handler.Create, args.params)
      .then(function(result) {
        var result = new RecurrentPaymentTools_Create_result({success: result});
        output.writeMessageBegin("Create", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        if (err instanceof ttypes.InvalidUser || err instanceof ttypes.InvalidPartyStatus || err instanceof ttypes.InvalidShopStatus || err instanceof ttypes.ShopNotFound || err instanceof ttypes.PartyNotFound || err instanceof ttypes.InvalidContractStatus || err instanceof ttypes.OperationNotPermitted || err instanceof ttypes.InvalidPaymentMethod) {
          var result = new RecurrentPaymentTools_Create_result(err);
          output.writeMessageBegin("Create", Thrift.MessageType.REPLY, seqid);
        } else {
          var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("Create", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.Create(args.params, function (err, result) {
      if (err == null || err instanceof ttypes.InvalidUser || err instanceof ttypes.InvalidPartyStatus || err instanceof ttypes.InvalidShopStatus || err instanceof ttypes.ShopNotFound || err instanceof ttypes.PartyNotFound || err instanceof ttypes.InvalidContractStatus || err instanceof ttypes.OperationNotPermitted || err instanceof ttypes.InvalidPaymentMethod) {
        var result = new RecurrentPaymentTools_Create_result((err != null ? err : {success: result}));
        output.writeMessageBegin("Create", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("Create", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

RecurrentPaymentToolsProcessor.prototype.process_Abandon = function(seqid, input, output) {
  var args = new RecurrentPaymentTools_Abandon_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.Abandon.length === 1) {
    Q.fcall(this._handler.Abandon, args.id)
      .then(function(result) {
        var result = new RecurrentPaymentTools_Abandon_result({success: result});
        output.writeMessageBegin("Abandon", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        if (err instanceof ttypes.InvalidUser || err instanceof ttypes.RecurrentPaymentToolNotFound || err instanceof ttypes.InvalidRecurrentPaymentToolStatus) {
          var result = new RecurrentPaymentTools_Abandon_result(err);
          output.writeMessageBegin("Abandon", Thrift.MessageType.REPLY, seqid);
        } else {
          var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("Abandon", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.Abandon(args.id, function (err, result) {
      if (err == null || err instanceof ttypes.InvalidUser || err instanceof ttypes.RecurrentPaymentToolNotFound || err instanceof ttypes.InvalidRecurrentPaymentToolStatus) {
        var result = new RecurrentPaymentTools_Abandon_result((err != null ? err : {success: result}));
        output.writeMessageBegin("Abandon", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("Abandon", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

RecurrentPaymentToolsProcessor.prototype.process_Get = function(seqid, input, output) {
  var args = new RecurrentPaymentTools_Get_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.Get.length === 1) {
    Q.fcall(this._handler.Get, args.id)
      .then(function(result) {
        var result = new RecurrentPaymentTools_Get_result({success: result});
        output.writeMessageBegin("Get", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        if (err instanceof ttypes.InvalidUser || err instanceof ttypes.RecurrentPaymentToolNotFound) {
          var result = new RecurrentPaymentTools_Get_result(err);
          output.writeMessageBegin("Get", Thrift.MessageType.REPLY, seqid);
        } else {
          var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("Get", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.Get(args.id, function (err, result) {
      if (err == null || err instanceof ttypes.InvalidUser || err instanceof ttypes.RecurrentPaymentToolNotFound) {
        var result = new RecurrentPaymentTools_Get_result((err != null ? err : {success: result}));
        output.writeMessageBegin("Get", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("Get", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

RecurrentPaymentToolsProcessor.prototype.process_GetEvents = function(seqid, input, output) {
  var args = new RecurrentPaymentTools_GetEvents_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.GetEvents.length === 2) {
    Q.fcall(this._handler.GetEvents, args.id, args.range)
      .then(function(result) {
        var result = new RecurrentPaymentTools_GetEvents_result({success: result});
        output.writeMessageBegin("GetEvents", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        if (err instanceof ttypes.InvalidUser || err instanceof ttypes.RecurrentPaymentToolNotFound || err instanceof ttypes.EventNotFound) {
          var result = new RecurrentPaymentTools_GetEvents_result(err);
          output.writeMessageBegin("GetEvents", Thrift.MessageType.REPLY, seqid);
        } else {
          var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("GetEvents", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.GetEvents(args.id, args.range, function (err, result) {
      if (err == null || err instanceof ttypes.InvalidUser || err instanceof ttypes.RecurrentPaymentToolNotFound || err instanceof ttypes.EventNotFound) {
        var result = new RecurrentPaymentTools_GetEvents_result((err != null ? err : {success: result}));
        output.writeMessageBegin("GetEvents", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("GetEvents", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

